name: WeChat Rest Builder

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Tidy mod
        run: go mod tidy
      
      - name: Download dependencies
        run: go mod download
  
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build webview
        working-directory: webview
        run: |
          sh build.sh

      - name: Build binary
        run: |
          sh build.sh

      - name: Create github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ./RELEASE.md
          draft: false
          prerelease: false
          files: |
            ./wechat-rest.zip
